language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - ALIEN_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=system
install:
  - cpanm --notest Alien::Build~1.19
script:
  - perl Makefile.PL && make manifest && perl Makefile.PL && make && make test
  
